import mongoose from 'mongoose'
const provider=new mongoose.Schema({
    username:{
        type:String,
        required:true,
        unique:true,
        trim:true,
        lowercase:true
    },
    name:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true
    },
    cnic:{
        type:String,
        unique: true,
        sparse: true,
        validate: {
            validator: function(v) {
                if (!v) return true;
                return /^\d{13}$/.test(v);
            },
            message: 'CNIC must be exactly 13 digits'
        }
    },
    password:{
        type:String,
        required:true
    },
    role:{
        type:String,
        default:"user"
    },
    experience:{
        type:String,
        default:''
    },
    category:{
        type:String,
        enum:['Plumber','Electronics','Electrician',''],
        default:''
    },
    charges:{
        type:Number,
        default:200,
        min:200,
        max:500
    },
    sandboxBankAccount:{
        accountNumber:{
            type:String,
            default:''
        },
        accountTitle:{
            type:String,
            default:''
        },
        bankName:{
            type:String,
            default:'ProConnect Sandbox Bank'
        },
        balance:{
            type:Number,
            default:0,
            min:0
        },
        currency:{
            type:String,
            default:'PKR'
        },
        isSetupComplete:{
            type:Boolean,
            default:false
        },
        transactions:[{
            bookingId:{
                type:mongoose.Schema.Types.ObjectId,
                ref:'Booking'
            },
            amount:{
                type:Number,
                default:0
            },
            type:{
                type:String,
                enum:['credit'],
                default:'credit'
            },
            description:{
                type:String,
                default:''
            },
            createdAt:{
                type:Date,
                default:Date.now
            }
        }]
    },
    location:{
        city:{
            type:String,
            default:''
        },
        area:{
            type:String,
            default:''
        },
        latitude:{
            type:Number
        },
        longitude:{
            type:Number
        }
    },
    ratingAverage:{
        type:Number,
        default:3.2
    },
    ratingCount:{
        type:Number,
        default:0
    },
    completionRate:{
        type:Number,
        default:70,
        min:0,
        max:100
    },
    isActive:{
        type:Boolean,
        default:false
    },
    warnings:{
        type:Number,
        default:0
    },
    isBanned:{
        type:Boolean,
        default:false
    },
    bannedAt:{
        type:Date,
        default:null
    },
    bannedReason:{
        type:String,
        default:''
    }
},{timestamps:true})
export default mongoose.model('provider',provider)
